name: 'Dev deployment'
run-name: 'Deploy to dev databricks environnement'
concurrency: 1
on:
  push:
    branches:
      - 'dev'
jobs:
  deploy:
    name: 'carburant'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main

      - run: databricks bundle validate
      - run: databricks bundle deploy
        working-directory: .
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev
