name: 'Dev deployment'
run-name: 'Deploy to dev by ${{ github.actor }}'

on:
  push:
    branches:
      - 'dev'

jobs:
  deploy:
    name: 'carburant'
    runs-on: ubuntu-latest
    env:
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_BUNDLE_ENV: dev
    steps:
      - name: 'Checkout du code'
        uses: actions/checkout@v4

      - name: 'Installation du CLI Databricks'
        uses: databricks/setup-cli@main

      - name: 'Validation du bundle'
        run: databricks bundle validate

      - name: 'Open job on URL'
        run: databricks bundle open carburant

      - name: 'Déploiement du bundle sur dev'
        run: databricks bundle deploy

      - name: 'Exécution du pipeline carburant'
        run: databricks bundle run carburant

      - name: 'Résumé du déploiement'
        run: |
          echo "### ✅ Déploiement et exécution réussis sur **dev**" >> $GITHUB_STEP_SUMMARY
          echo "- Auteur : **${{ github.actor }}**" >> $GITHUB_STEP_SUMMARY
          echo "- Bundle : \`fuel_prices_lakehouse\`" >> $GITHUB_STEP_SUMMARY
          echo "- Commit : \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY